### ISSUE TITLE
Do not have oidc_client_identifier in the URI to initiate log in

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#12]
Rather than placing oidc_client_identifier in the log in, we should use an alias and look up the identifier. So instead of having something like this:

`/login/oidc?oidc_client_identifier=https://accounts.google.com/o/oauth2/auth:309185963195-29o0gs3ptpfjevd20o387ssrhogbc8t5.apps.googleusercontent.com`

we would have something like:

`/login/oidc/google`

Relates to #1

**Comment by jgrandja** [comment]
Fixed as a result of #1
