### ISSUE TITLE
InMemoryClientConfigurationRepository should use a map

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#14]
InMemoryClientConfigurationRepository would be a lot simpler if ClientConfiguration was stored in a Map with the key being the alias.

**Comment by jgrandja** [comment]
Very true. Will apply that.

**Comment by jgrandja** [comment]
I added another operation on `ClientConfigurationRepository`

`ClientConfiguration getConfigurationById(String clientId)`

which invalidates the original issue as it wouldn't make sense to have 2 Map's keyed by alias and the other by clientId.

Will leave as is unless you have another idea?
