### ISSUE TITLE
Componentize AuthorizationUtil

### ISSUE THREAD

**Issue by jgrandja** [jgrandja/oauth2-samples#45]
All methods in `AuthorizationUtil` are currently static with package access.

It may be useful to move some of these methods into new/existing classes to allow for better reuse.

**Comment by rwinch** [comment]
Methods for saving and retrieving things in session should be an interface. This ensures that `AuthorizationCodeGrantProcessingFilter` and `AuthorizationRequestRedirectFilter` are on the same page as to how the authorization request is being saved / retrieved.
