### ISSUE TITLE
Delete AuthorizationRequestRedirectFilter's AuthorizationRequestMatcher

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#49]
I think we can just using an AntPathMatcher with a pattern like `/login/oauth2/{alias}` for matching and if the client alias doesn't exist send a bad response back. This will

* improve performance of having to iterate over all the configurations
* simplify the code
* we can extract the client code using `RequestVariableExtractor`

**Comment by jgrandja** [comment]
Great suggestion @rwinch. I ended up using `AntPathRequestMatcher` and this reduced and simplified the code. Thanks!
