### ISSUE TITLE
Remove the protected methods in AuthorizationRequestRedirectFilter

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#50]
All of the logic should in `AuthorizationRequestRedirectFilter` should be controller logic or have a strategy that allows the user to customize the behavior

**Comment by jgrandja** [comment]
`protected` methods have been removed and consolidated the logic into the  `obtainAuthorization` method which is `private`.

The only strategy at this point is `AuthorizationRequestUriBuilder` but we may expose a strategy for generating the `state` parameter at a later point.
