### ISSUE TITLE
Tokens does not match the Specification

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#52]
The Tokens construct seems a bit out of place and does not match any of the existing OAuth terminology. I wonder if it makes more sense to be an `AccessTokenResponse` (or something similar). Another issue is that `Tokens` is currently missing things like refresh token, additional parameters, etc.

**Comment by jgrandja** [comment]
@rwinch I modified `AuthorizationGrantTokenExchanger`to return `TokenResponseAttributes` instead of `Tokens`. This is aligned with the _Access Token Response_ per spec. 

Also, I changed the generic argument type.

Let me know what you think of this change.
