### ISSUE TITLE
Ensure Domain Objects match specification

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#56]
It seems like some of the domain objects don't match the specification. An example is `Tokens` see #52. Another example is the `client.configuration`  package and its associated classes should probably use registration rather than configuration. This will also ensure we can easily know the difference between Spring Configuration and the OAuth client registrations by looking at the package / class name.

**Comment by jgrandja** [comment]
I wasn't totally satisfied with the `ClientConfiguration` name and figured it would be changed at some point. `ClientRegistration` aligns with the OAuth2 and OpenID Connect specs so will go with that.
