### ISSUE TITLE
Simplify Java Configuration

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#6]
Right now a user needs to know all the internal details of the implementation. Ideally, we would have something like this:

```java
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.antMatchers("/", "/oauth2/client/**").permitAll()
			.anyRequest().authenticated()
			.and()
		.apply(oauth2Login());
}
```

This can be done by creating a subclass of `AbstractHttpConfigurer` which is public as of Spring Security 4.2.0.RELEASE

**Comment by jgrandja** [comment]
@rwinch I added `AuthorizationRequestRedirectFilterConfigurer` and `AuthorizationCodeGrantFilterConfigurer`. 

The sample configs are now very straightforward. However, I feel like we can further re-factor into a single `SecurityConfigurer`. 

For example, an `OAuth2SecurityConfigurer` will create/configure  `AuthorizationRequestRedirectFilterConfigurer`, `AuthorizationCodeGrantFilterConfigurer`, and any future OAuth2 client-specific filters and then `apply()` them all to `HttpSecurity`. The static method exposed would be `oauth2()`.

Furthermore, I'm also feeling that it may make sense to create a **_Composite Filter_** that composes all OAuth2 client filters. This may make it easier to manage the ordering and execution of the filters. It would be similar to `FilterChainProxy` but would contain all OAuth2-specific filter functionality.

In a nut shell,  `OAuth2SecurityConfigurer` would configure `HttpSecurity` by adding a   `OAuth2SecurityFilter` which is composed of `AuthorizationRequestRedirectFilter` and `AuthorizationCodeGrantFilter` initially (and any future OAuth2 client-specific filters).

What are your thoughts on these ideas?

**Comment by rwinch** [comment]
> The sample configs are now very straightforward. However, I feel like we can further re-factor into a single SecurityConfigurer.
>
> For example, an OAuth2SecurityConfigurer will create/configure AuthorizationRequestRedirectFilterConfigurer, AuthorizationCodeGrantFilterConfigurer, and any future OAuth2 client-specific filters and then apply() them all to HttpSecurity. The static method exposed would be oauth2().

I think this is a good idea. Additionally, I think the DSL (SecurityConfigurer) should be less about what you are doing with APIs specific to Spring Security and read more like the OAuth specification.

I would give a bit more thought about `oauth2` method name. It might be `oauth2Client` so it won't be confused with configuring an authorization server or resource server.

> Furthermore, I'm also feeling that it may make sense to create a Composite Filter that composes all OAuth2 client filters. This may make it easier to manage the ordering and execution of the filters. It would be similar to FilterChainProxy but would contain all OAuth2-specific filter functionality.

I'm not so sure about this. This will likely make Spring Security even more confusing having nested composite filters and doesn't align with how things currently work. If we did decide to do it, we could use `FilterChainProxy` rather than creating a new `Filter`

**Comment by jgrandja** [comment]
Yes `oauth2Client` is better to prevent any clashes. And good idea on keeping the DSL reading more like the spec language.

Agreed that another composite filter would potentially confuse things more but it may be useful depending on how many filters turn out during this dev. I'll leave it for now and see where things go.
