### ISSUE TITLE
Remove AuthorizationRequestRedirectStrategy in favor of AuthenticationEntryPoint

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#8]
I think we can remove `AuthorizationRequestRedirectStrategy` in favor of using `AuthenticationEntryPoint`. This would allow redirecting directly to the OAuth IdP rather than a middle man (i.e. the `ExceptionTranslationFilter` requires an `AuthenticationEntryPoint`).

If we end up needing to use the redirect for other situations (I suspect we might) at that time we can extract out a base class or a utility class.

**NOTE**: I should note that I'm not entirely convinced of this since it isn't exactly authentication, but I think it makes sense.

**Comment by jgrandja** [comment]
`AuthorizationRequestRedirectStrategy` was replaced by `AuthorizationRequestUriBuilder` in bdad5f4

Please review and let me know if this issue is still applicable?

**Comment by jgrandja** [comment]
@rwinch I believe we can close this issue as it's outdated?
