### ISSUE TITLE
Question: Will this be a replacement for spring-social?

### ISSUE THREAD

**Issue by jbellmann** [jgrandja/oauth2-samples#80]
How does this project relates to spring-social? It seems both handling the 'OAuth-Flow' to connect to different providers. Is there also 'token-store' planned or already in place?

Thanks
Jörg

**Comment by jgrandja** [comment]
Hi @jbellmann This project/repository has been a sandbox for the new OAuth2 API that is about to get merged into Spring Security 5.0. You can track the issue [here](https://github.com/spring-projects/spring-security/issues/3907). Spring Social will eventually be updated to use this lower level API. Also, the current Spring Security OAuth project is in maintenance mode and we are limiting new features. Efforts will be focused on the new OAuth2 API within the Spring Security project.
